### ISSUE TITLE
想问下example的路径是在哪里设置的？

### ISSUE THREAD

**Issue by oskar0812** [GuoPingPan/Habitat-Sim-Usage-Chinese#1]
作者写的好棒！
我现在想自己设定路径然后去渲染replica的数据集，想请问一下在哪里可以设定漫游路径以及如何在savepng的同时保存当前相机的内外参呢？

**Comment by GuoPingPan** [comment]
> 作者写的好棒！ 我现在想自己设定路径然后去渲染replica的数据集，想请问一下在哪里可以设定漫游路径以及如何在savepng的同时保存当前相机的内外参呢？

Hi，请问你所指的漫游路径是什么？
我觉得如果你想用 habitat-lab 制作数据集的话，可以参考：
https://github.com/facebookresearch/habitat-lab/blob/a5acc78e28cbe2e9ca31d5442f13c48a053b6bd7/examples/tutorials/colabs/Habitat_Interactive_Tasks.ipynb

对于相机参数
1. 内参参考：https://aihabitat.org/docs/habitat-lab/view-transform-warp.html
> 其实这里我也还没弄懂为什么是 cx=0、cy=0
2. 外参其实就当前的位姿：
  a.通过 habita-lab 构建 env 可这样获得： env.sim.get_agent_state(0)
  b.通过 habitat-sim 构建 sim 可以这样：sim.get_agent_state(0)

**Comment by oskar0812** [comment]
> > 作者写的好棒！ 我现在想自己设定路径然后去渲染replica的数据集，想请问一下在哪里可以设定漫游路径以及如何在savepng的同时保存当前相机的内外参呢？
> 
> Hi，请问你所指的漫游路径是什么？ 我觉得如果你想用 habitat-lab 制作数据集的话，可以参考： https://github.com/facebookresearch/habitat-lab/blob/a5acc78e28cbe2e9ca31d5442f13c48a053b6bd7/examples/tutorials/colabs/Habitat_Interactive_Tasks.ipynb
> 
> 对于相机参数
> 
> 1. 内参参考：https://aihabitat.org/docs/habitat-lab/view-transform-warp.html
> 
> > 其实这里我也还没弄懂为什么是 cx=0、cy=0
> 
> 2. 外参其实就当前的位姿：
>    a.通过 habita-lab 构建 env 可这样获得： env.sim.get_agent_state(0)
>    b.通过 habitat-sim 构建 sim 可以这样：sim.get_agent_state(0)

感谢您的回复！因为我用的是没有显示终端的服务器去运行代码的，所以我指的修改漫游路径就是如何通过修改代码去设定摄像机的运动轨迹，因为我看到example可以输出机器人的运动路径。
请问您是在Linux系统的电脑上运行程序的吗？因为其实我用没有显示终端的服务器去运行代码时在配置环境上遇到了非常多的问题，且用这种方式渲染数据集十分不方便，不知道您有什么建议吗？以及有没有制作Replica数据集的建议？

**Comment by GuoPingPan** [comment]
1. 你可以把你看的那个 example 的代码链接发一下吗？我可能不是很清楚你所说的保存轨迹是哪个
2. 其实我觉得不用渲染数据集也是 ok 的，因为我实际在用的时候就是链接的远程服务器，不过我还是安装全的版本，不是 headless，我觉得关键是能够获得对应的图像数据就行了。

**Comment by oskar0812** [comment]
> example的代码就是Habitat-sim/example/example.py文件，它在headless运行的时候会输出一组机器人运动转向的轨迹，我现在看起来它好像是随机设定的。
我现在就是想用Habitat-sim跑一组replica的数据集用于新视点合成的训练测试，输出RGBD图像以及相机内外参，或者您有现成的运行脚本嘛？感激不尽！

**Comment by GuoPingPan** [comment]
> 

你是想做nerf的数据集吗？感觉你要手动随机设置机器人当前的位置然后读取传感器的图像，相机内参其实就是根据fov算的
```
    focal = frame_width / 2. / np.tan(np.deg2rad(fov / 2.))
    xc = (frame_width - 1.) / 2.
    yc = (frame_height - 1.) / 2.
```
> 我其实感觉这个拿来做 nerf 数据集比较麻烦

**Comment by GuoPingPan** [comment]
突然找到了如何获得当前位置下的图像的函数
```
env.habitat_env.sim.get_observations_at(
                position, rotation, keep_agent_at_new_pose=True,
            )
```

**Comment by oskar0812** [comment]
> > 
> 
> 你是想做nerf的数据集吗？感觉你要手动随机设置机器人当前的位置然后读取传感器的图像，相机内参其实就是根据fov算的
> 
> ```
>     focal = frame_width / 2. / np.tan(np.deg2rad(fov / 2.))
>     xc = (frame_width - 1.) / 2.
>     yc = (frame_height - 1.) / 2.
> ```
> 
> > 我其实感觉这个拿来做 nerf 数据集比较麻烦
是的，但是目前也没找到更适合的室内数据集了。十分感谢！这个frame_width是图片分辨率的宽吗？为什么要-1啊？

**Comment by GuoPingPan** [comment]
> > > 
> > 
> > 
> > 你是想做nerf的数据集吗？感觉你要手动随机设置机器人当前的位置然后读取传感器的图像，相机内参其实就是根据fov算的
> > ```
> >     focal = frame_width / 2. / np.tan(np.deg2rad(fov / 2.))
> >     xc = (frame_width - 1.) / 2.
> >     yc = (frame_height - 1.) / 2.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > > 我其实感觉这个拿来做 nerf 数据集比较麻烦
> > > 是的，但是目前也没找到更适合的室内数据集了。十分感谢！这个frame_width是图片分辨率的宽吗？为什么要-1啊？

图像的索引是0~width-1

**Comment by oskar0812** [comment]
了解了，十分感谢！

**Comment by GuoPingPan** [comment]
我想问你一下，你有没有下载MP3D的方法呀？我发邮件了但是还没有回复

**Comment by oskar0812** [comment]
大概发完邮件要等一段时间，一两天的样子会回复邮件的

**Comment by GuoPingPan** [comment]
哈哈哈你要不直接把那个下载连接发我？难道他是将数据集发过来吗？

**Comment by GuoPingPan** [comment]
最近赶着做一些东西

**Comment by oskar0812** [comment]
大概发完邮件要等一段时间，一两天的样子会回复邮件的

**Comment by oskar0812** [comment]
发你gmail邮箱了你看看能用吗

**Comment by GuoPingPan** [comment]
可能不太行。
hhh加个联系方式之后继续交流！
