### ISSUE TITLE
MP3d中.glb文件

### ISSUE THREAD

**Issue by SepMJ** [GuoPingPan/Habitat-Sim-Usage-Chinese#2]
您好，请问您在下载MP3d数据集的时候，压缩包内有.glb文件，为什么我的house id下面是没有后缀为.glb的文件。

**Comment by GuoPingPan** [comment]
我是通过这里下载的：https://github.com/facebookresearch/habitat-sim/blob/main/DATASETS.md#matterport3d-mp3d-dataset
好像一个是专门给 habitat 用的压缩包，另外就是下载完整的 MP3D 数据集

> 上面链接提示： You only need the habitat zip archive and not the entire Matterport3D dataset.

**Comment by jiaomengzhang** [comment]
谢谢您，这个网址我也看到了，下载了habitat，有很多个id,但是每个id下面并没有看到.glb后缀的文件，类似于这样17DRP5sb8fy/17DRP5sb8fy.glb  完整的MP3d数据集大概需要1.3TB吧，我就是特别好奇这个.glb后缀的文件为啥我没找到，所以想请教一下您。

**Comment by GuoPingPan** [comment]
> 您好，请问您在下载MP3d数据集的时候，压缩包内有.glb文件，为什么我的house id下面是没有后缀为.glb的文件。

你好，你这边有下载 MP3D 的链接吗？

**Comment by Magic-Pony** [comment]
> 我是通过这里下载的：https://github.com/facebookresearch/habitat-sim/blob/main/DATASETS.md#matterport3d-mp3d-dataset 好像一个是专门给 habitat 用的压缩包，另外就是下载完整的 MP3D 数据集
> 
> > 上面链接提示： You only need the habitat zip archive and not the entire Matterport3D dataset.

我也遇到了这个困惑。按照这个链接里的指示，我用habitat-sim的datasets_download脚本能下载一个mp3d场景数据集，里面有.glb文件。但我还想要其他场景的，查看这个脚本的代码，里面就没给下载的实现了。只能根据上述链接指示，填表格，发邮件，然后获取回信中的数据集下载脚本download_mp.py。但用这个脚本下载出来的mp3d数据集，只有每个场景下的各个传感器数据，用压缩包保存。所有压缩包中都没有.glb文件。
我当时的下载指令是：
python download-mp.py -o  /home/lcy-magic/VisualNav_TEST/onav_rim/data/scene_datasets/mp3d --id 17DRP5sb8fy
可能因为我没有参照上述链接的模板：python download_mp.py --task habitat -o path/to/download/
的原因。我将运行python download_mp.py --task habitat -o /home/lcy-magic/VisualNav_TEST/onav_rim/data/scene_datasets/mp3d --id 17DRP5sb8fy
试一试。
试好了，果然在多了一个tasks文件夹，里面有各个场景的文件夹，其中就有.glb文件

**Comment by gqsmmz** [comment]
> > 我是通过这里下载的：https://github.com/facebookresearch/habitat-sim/blob/main/DATASETS.md#matterport3d-mp3d-dataset 好像一个是专门给 habitat 用的压缩包，另外就是下载完整的 MP3D 数据集
> > > 上面链接提示： You only need the habitat zip archive and not the entire Matterport3D dataset.
> 
> 我也遇到了这个困惑。按照这个链接里的指示，我用habitat-sim的datasets_download脚本能下载一个mp3d场景数据集，里面有.glb文件。但我还想要其他场景的，查看这个脚本的代码，里面就没给下载的实现了。只能根据上述链接指示，填表格，发邮件，然后获取回信中的数据集下载脚本download_mp.py。但用这个脚本下载出来的mp3d数据集，只有每个场景下的各个传感器数据，用压缩包保存。所有压缩包中都没有.glb文件。 我当时的下载指令是： python download-mp.py -o /home/lcy-magic/VisualNav_TEST/onav_rim/data/scene_datasets/mp3d --id 17DRP5sb8fy 可能因为我没有参照上述链接的模板：python download_mp.py --task habitat -o path/to/download/ 的原因。我将运行python download_mp.py --task habitat -o /home/lcy-magic/VisualNav_TEST/onav_rim/data/scene_datasets/mp3d --id 17DRP5sb8fy 试一试。 试好了，果然在多了一个tasks文件夹，里面有各个场景的文件夹，其中就有.glb文件

您好，我下载后确实多了一个tasks文件夹，但是里面只有一个没有后缀的文件，没有.glb文件，请问是为什么呜呜。用的语句是`python download_mp.py --task habitat -o data/scene_datasets/mp3d/ --id 17DRP5sb8fy`。

![image](https://github.com/user-attachments/assets/1ae53be5-b765-4186-89e5-fa20b26c3207)

**Comment by MrOK24** [comment]
我也遇到了相同的问题 请问该如何解决呢
